export const SkillsForSignUpPage = [
  "Python",
  "JavaScript",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Go",
  "Swift",
  "TypeScript",
  "R",
  "Kotlin",
  "MATLAB",
  "Rust",
  "SQL",
  "HTML",
  "CSS",
  "React.js",
  "Angular",
  "Vue.js",
  "Next.js",
  "Django",
  "Flask",
  "Node.js",
  "Express.js",
  "Bootstrap",
  "Tailwind CSS",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Firebase",
  "Redis",
  "Oracle",
  "Microsoft SQL Server",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Jupyter Notebooks",
  "OpenCV",
  "Data Visualization",
  "Model Deployment",
  "AWS",
  "Google Cloud",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Terraform",
  "GitHub Actions",
  "CI/CD Pipelines",
  "Penetration Testing",
  "Network Security",
  "Ethical Hacking",
  "Wireshark",
  "Nmap",
  "Vulnerability Assessment",
  "SOC Operations",
  "Encryption Techniques",
  "Git",
  "GitHub",
  "Bash",
  "PowerShell",
  "VS Code",
  "Figma",
  "Postman",
  "Jira",
  "Notion",
  "Excel (Advanced)",
  "Tableau",
  "Power BI",
  "Market Research",
  "Business Analysis",
  "Competitive Benchmarking",
  "Product Management",
  "Operations Strategy",
  "Financial Modeling",
  "Critical Thinking",
  "Root Cause Analysis",
  "Data Interpretation",
  "Decision Trees",
  "Risk Assessment",
  "Public Speaking",
  "Written Communication",
  "Active Listening",
  "Technical Writing",
  "Presentation Design",
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "Stakeholder Management",
  "Cross-Functional Team Leadership",
  "Resource Allocation",
  "UI/UX Design",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "Copywriting",
  "Content Strategy",
  "User Research",
  "Storyboarding",
  "Video Editing",
  "Teamwork",
  "Adaptability",
  "Time Management",
  "Conflict Resolution",
  "Leadership",
  "Emotional Intelligence",
  "Self-Motivation",
  "Reliability",
  "Empathy",
];
